#!/usr/bin/env bash
# configure_mqtt.sh - Interactive MQTT configuration tool
#
# This script creates/updates /opt/rpi-lab/.env with MQTT settings
# for connecting to Home Assistant MQTT broker.
#
# Usage: sudo bash install/configure_mqtt.sh

set -euo pipefail

APP_DIR="${APP_DIR:-/opt/rpi-lab}"
ENV_FILE="$APP_DIR/.env"

# Colors
COLOR_GRN='\033[0;32m'
COLOR_YLW='\033[0;33m'
COLOR_BLU='\033[0;34m'
COLOR_RST='\033[0m'

log() { echo -e "${COLOR_BLU}➤${COLOR_RST} $*"; }
ok() { echo -e "${COLOR_GRN}✓${COLOR_RST} $*"; }
warn() { echo -e "${COLOR_YLW}⚠${COLOR_RST} $*"; }

echo ""
echo "============================================================================"
echo "  MQTT Configuration Tool"
echo "============================================================================"
echo ""
log "This tool configures MQTT settings for Home Assistant integration."
log "Configuration will be saved to: $ENV_FILE"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    warn "This script should be run with sudo for proper file permissions"
    echo ""
    read -p "Continue anyway? [y/N]: " -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
fi

# Load existing config if available
if [ -f "$ENV_FILE" ]; then
    ok "Existing configuration found: $ENV_FILE"
    echo ""
    log "Current settings:"
    grep -E "^(MQTT_|DEVICE_|UPDATE_)" "$ENV_FILE" | sed 's/^/  /' || true
    echo ""
    read -p "Update configuration? [Y/n]: " -r
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        exit 0
    fi
    echo ""
    
    # Source existing values
    source "$ENV_FILE" 2>/dev/null || true
fi

# Prompt for settings
echo "============================================================================"
echo "  MQTT Broker Settings"
echo "============================================================================"
echo ""

read -p "MQTT Broker hostname/IP [${MQTT_BROKER:-homeassistant.local}]: " MQTT_BROKER_INPUT
MQTT_BROKER="${MQTT_BROKER_INPUT:-${MQTT_BROKER:-homeassistant.local}}"

read -p "MQTT Port [${MQTT_PORT:-1883}]: " MQTT_PORT_INPUT
MQTT_PORT="${MQTT_PORT_INPUT:-${MQTT_PORT:-1883}}"

read -p "MQTT Username [${MQTT_USER:-}]: " MQTT_USER_INPUT
MQTT_USER="${MQTT_USER_INPUT:-${MQTT_USER:-}}"

read -sp "MQTT Password [${MQTT_PASSWORD:+********}]: " MQTT_PASSWORD_INPUT
echo ""
MQTT_PASSWORD="${MQTT_PASSWORD_INPUT:-${MQTT_PASSWORD:-}}"

echo ""
echo "============================================================================"
echo "  Device Settings"
echo "============================================================================"
echo ""

read -p "Device Name [${DEVICE_NAME:-rpi_lab}]: " DEVICE_NAME_INPUT
DEVICE_NAME="${DEVICE_NAME_INPUT:-${DEVICE_NAME:-rpi_lab}}"

read -p "Update Interval (seconds) [${UPDATE_INTERVAL:-60}]: " UPDATE_INTERVAL_INPUT
UPDATE_INTERVAL="${UPDATE_INTERVAL_INPUT:-${UPDATE_INTERVAL:-60}}"

# Create .env file
echo ""
log "Writing configuration to $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# MQTT Configuration for Home Assistant Integration
# Generated by configure_mqtt.sh on $(date)

# MQTT Broker Settings
MQTT_BROKER=$MQTT_BROKER
MQTT_PORT=$MQTT_PORT
MQTT_USER=$MQTT_USER
MQTT_PASSWORD=$MQTT_PASSWORD
MQTT_TOPIC_PREFIX=homeassistant

# Device Settings
DEVICE_NAME=$DEVICE_NAME
UPDATE_INTERVAL=$UPDATE_INTERVAL

# Sensor Calibration (optional - see docs/TROUBLESHOOTING.md)
# BME690_ENABLE_GAS=1
# BME690_HUM_SCALE=1.0
# BME690_HUM_OFFSET=0.0
EOF

# Set proper permissions
chmod 600 "$ENV_FILE"
chown root:root "$ENV_FILE" 2>/dev/null || true

ok "Configuration saved!"
echo ""

# Test connection
echo "============================================================================"
echo "  Connection Test"
echo "============================================================================"
echo ""
log "Testing connection to $MQTT_BROKER:$MQTT_PORT..."

if command -v nc &> /dev/null; then
    if timeout 3 nc -zv "$MQTT_BROKER" "$MQTT_PORT" 2>&1 | grep -q "succeeded\|open"; then
        ok "Connection successful!"
    else
        warn "Could not connect to $MQTT_BROKER:$MQTT_PORT"
        warn "Verify broker is reachable and port is correct"
    fi
else
    warn "nc (netcat) not installed - skipping connection test"
fi

echo ""

# Restart service if running
if systemctl is-active --quiet mqtt_publisher.service; then
    log "Restarting mqtt_publisher.service..."
    systemctl restart mqtt_publisher.service
    ok "Service restarted"
    echo ""
    log "Checking service status..."
    sleep 2
    
    # Show recent logs
    journalctl -u mqtt_publisher.service -n 10 --no-pager
    echo ""
    
    if systemctl is-active --quiet mqtt_publisher.service; then
        ok "Service is running!"
    else
        warn "Service failed to start - check logs above"
    fi
else
    warn "mqtt_publisher.service is not running"
    log "Start it with: sudo systemctl start mqtt_publisher.service"
fi

echo ""
echo "============================================================================"
echo "  Configuration Complete"
echo "============================================================================"
echo ""
ok "MQTT settings saved to: $ENV_FILE"
ok "To reconfigure: sudo bash $APP_DIR/install/configure_mqtt.sh"
ok "View logs: sudo journalctl -u mqtt_publisher.service -f"
ok "Documentation: $APP_DIR/docs/HOME_ASSISTANT_MQTT.md"
echo ""
